[2025-04-22T23:24:21.532+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T23:24:21.555+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_project.upload_files_project_02 manual__2025-04-22T23:23:43.965680+00:00 [queued]>
[2025-04-22T23:24:21.567+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_project.upload_files_project_02 manual__2025-04-22T23:23:43.965680+00:00 [queued]>
[2025-04-22T23:24:21.569+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-22T23:24:21.585+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_files_project_02> on 2025-04-22 23:23:43.965680+00:00
[2025-04-22T23:24:21.591+0000] {standard_task_runner.py:72} INFO - Started process 1788 to run task
[2025-04-22T23:24:21.596+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_files_project', 'upload_files_project_02', 'manual__2025-04-22T23:23:43.965680+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/script-upload_files_projeto_grupo_01-DAGs.py', '--cfg-path', '/tmp/tmpy541g72v']
[2025-04-22T23:24:21.599+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask upload_files_project_02
[2025-04-22T23:24:21.675+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_files_project.upload_files_project_02 manual__2025-04-22T23:23:43.965680+00:00 [running]> on host e50052774237
[2025-04-22T23:24:21.761+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_files_project' AIRFLOW_CTX_TASK_ID='upload_files_project_02' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:23:43.965680+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T23:23:43.965680+00:00'
[2025-04-22T23:24:21.764+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T23:24:23.206+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/multirio-2445/LD-2445-PE-PAD-PLN-GRC-001_R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '4174603'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'eca0228c-1fd0-11f0-b6bf-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:24:26.725+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:24:26 GMT'
    'ETag': '"0x8DD81F4D2D11E00"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '87f0d5c6-101e-0024-1fdd-b3e46b000000'
    'x-ms-client-request-id': 'eca0228c-1fd0-11f0-b6bf-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:24:25 GMT'
[2025-04-22T23:24:26.728+0000] {logging_mixin.py:190} INFO - Arquivo 'LD-2445-PE-PAD-PLN-GRC-001_R0.xlsx' enviado com sucesso para o container 'multirio-2445'.
[2025-04-22T23:24:26.949+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/multirio-2445/CS-2445-PE-PAD-PLN-GRC-001.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '56186'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'eedb34ec-1fd0-11f0-b6bf-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:24:28.441+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:24:28 GMT'
    'ETag': '"0x8DD81F4D3DC7F3E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ae158cd5-a01e-0053-5bdd-b331ff000000'
    'x-ms-client-request-id': 'eedb34ec-1fd0-11f0-b6bf-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:24:27 GMT'
[2025-04-22T23:24:28.443+0000] {logging_mixin.py:190} INFO - Arquivo 'CS-2445-PE-PAD-PLN-GRC-001.xlsx' enviado com sucesso para o container 'multirio-2445'.
[2025-04-22T23:24:28.520+0000] {logging_mixin.py:190} INFO - Erro ao enviar o arquivo 'faturamento_2445.xlsx': [Errno 2] No such file or directory: '/opt/***/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/MULTIRIO/faturamento_2445.xlsx'
[2025-04-22T23:24:28.523+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/script-upload_files_projeto_grupo_01-DAGs.py", line 74, in upload_files_multirio
    upload_to_blob(
  File "/opt/airflow/dags/script-upload_files_projeto_grupo_01-DAGs.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/script-upload_files_projeto_grupo_01-DAGs.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/MULTIRIO/faturamento_2445.xlsx'
[2025-04-22T23:24:28.540+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=upload_files_project, task_id=upload_files_project_02, run_id=manual__2025-04-22T23:23:43.965680+00:00, execution_date=20250422T232343, start_date=20250422T232421, end_date=20250422T232428
[2025-04-22T23:24:28.579+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T23:24:28.582+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 59 for task upload_files_project_02 ([Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/MULTIRIO/faturamento_2445.xlsx'; 1788)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/script-upload_files_projeto_grupo_01-DAGs.py", line 74, in upload_files_multirio
    upload_to_blob(
  File "/opt/airflow/dags/script-upload_files_projeto_grupo_01-DAGs.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/script-upload_files_projeto_grupo_01-DAGs.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/MULTIRIO/faturamento_2445.xlsx'
[2025-04-22T23:24:28.625+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T23:24:28.665+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-22T23:24:28.672+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
