[2025-04-22T23:32:37.523+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T23:32:37.542+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_project_01.upload_files_project_01 manual__2025-04-22T23:31:59.302851+00:00 [queued]>
[2025-04-22T23:32:37.552+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_project_01.upload_files_project_01 manual__2025-04-22T23:31:59.302851+00:00 [queued]>
[2025-04-22T23:32:37.553+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-22T23:32:37.568+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_files_project_01> on 2025-04-22 23:31:59.302851+00:00
[2025-04-22T23:32:37.574+0000] {standard_task_runner.py:72} INFO - Started process 1918 to run task
[2025-04-22T23:32:37.579+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_files_project_01', 'upload_files_project_01', 'manual__2025-04-22T23:31:59.302851+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/upload_files_project_01.py', '--cfg-path', '/tmp/tmp5cjyeo7f']
[2025-04-22T23:32:37.582+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask upload_files_project_01
[2025-04-22T23:32:37.644+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_files_project_01.upload_files_project_01 manual__2025-04-22T23:31:59.302851+00:00 [running]> on host e50052774237
[2025-04-22T23:32:37.739+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_files_project_01' AIRFLOW_CTX_TASK_ID='upload_files_project_01' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:31:59.302851+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T23:31:59.302851+00:00'
[2025-04-22T23:32:37.742+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T23:32:39.552+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/brasfels-2446/LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '4187310'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '14787a1a-1fd2-11f0-be75-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:32:42.442+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:32:42 GMT'
    'ETag': '"0x8DD81F5FA4C2E02"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cdc49db5-b01e-004f-73de-b3639f000000'
    'x-ms-client-request-id': '14787a1a-1fd2-11f0-be75-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:32:41 GMT'
[2025-04-22T23:32:42.444+0000] {logging_mixin.py:190} INFO - Arquivo 'LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx' enviado com sucesso para o container 'brasfels-2446'.
[2025-04-22T23:32:42.662+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/brasfels-2446/CS-2446-PE-CAR-PLN-GRC-001-R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '80279'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '16530de6-1fd2-11f0-be75-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:32:44.021+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:32:43 GMT'
    'ETag': '"0x8DD81F5FB46B225"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '30a31a60-201e-0062-74de-b3d0ec000000'
    'x-ms-client-request-id': '16530de6-1fd2-11f0-be75-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:32:43 GMT'
[2025-04-22T23:32:44.023+0000] {logging_mixin.py:190} INFO - Arquivo 'CS-2446-PE-CAR-PLN-GRC-001-R0.xlsx' enviado com sucesso para o container 'brasfels-2446'.
[2025-04-22T23:32:44.052+0000] {logging_mixin.py:190} INFO - Erro ao enviar o arquivo 'faturamento_2446.xlsx': [Errno 2] No such file or directory: '/opt/***/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'
[2025-04-22T23:32:44.055+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/upload_files_project_01.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/upload_files_project_01.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/upload_files_project_01.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'
[2025-04-22T23:32:44.070+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=upload_files_project_01, task_id=upload_files_project_01, run_id=manual__2025-04-22T23:31:59.302851+00:00, execution_date=20250422T233159, start_date=20250422T233237, end_date=20250422T233244
[2025-04-22T23:32:44.103+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T23:32:44.106+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task upload_files_project_01 ([Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'; 1918)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/upload_files_project_01.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/upload_files_project_01.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/upload_files_project_01.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'
[2025-04-22T23:32:44.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T23:32:44.137+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T23:32:44.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
