[2025-04-22T23:00:15.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T23:00:15.886+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_projetos_grupo_2.upload_projeto_2244_EMAP manual__2025-04-22T23:00:15.025221+00:00 [queued]>
[2025-04-22T23:00:15.896+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_projetos_grupo_2.upload_projeto_2244_EMAP manual__2025-04-22T23:00:15.025221+00:00 [queued]>
[2025-04-22T23:00:15.897+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-22T23:00:15.914+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_projeto_2244_EMAP> on 2025-04-22 23:00:15.025221+00:00
[2025-04-22T23:00:15.921+0000] {standard_task_runner.py:72} INFO - Started process 1430 to run task
[2025-04-22T23:00:15.927+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_files_projetos_grupo_2', 'upload_projeto_2244_EMAP', 'manual__2025-04-22T23:00:15.025221+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_projeto_grupo-02.py', '--cfg-path', '/tmp/tmp4k_cfax5']
[2025-04-22T23:00:15.930+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask upload_projeto_2244_EMAP
[2025-04-22T23:00:15.991+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_files_projetos_grupo_2.upload_projeto_2244_EMAP manual__2025-04-22T23:00:15.025221+00:00 [running]> on host e50052774237
[2025-04-22T23:00:16.071+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='arthur.lopes' AIRFLOW_CTX_DAG_ID='upload_files_projetos_grupo_2' AIRFLOW_CTX_TASK_ID='upload_projeto_2244_EMAP' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:00:15.025221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T23:00:15.025221+00:00'
[2025-04-22T23:00:16.074+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T23:00:16.091+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/dag_projeto_grupo-02.py", line 34, in upload_files_2244_EMAP
    arquivos = {
TypeError: unhashable type: 'dict'
[2025-04-22T23:00:16.105+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=upload_files_projetos_grupo_2, task_id=upload_projeto_2244_EMAP, run_id=manual__2025-04-22T23:00:15.025221+00:00, execution_date=20250422T230015, start_date=20250422T230015, end_date=20250422T230016
[2025-04-22T23:00:16.134+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T23:00:16.136+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task upload_projeto_2244_EMAP (unhashable type: 'dict'; 1430)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/dag_projeto_grupo-02.py", line 34, in upload_files_2244_EMAP
    arquivos = {
TypeError: unhashable type: 'dict'
[2025-04-22T23:00:16.183+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T23:00:16.216+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T23:00:16.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
